#!/usr/bin/env python3
"""Add 10 new posts to posts.json, using existing images where available."""
import json
import os

POSTS_FILE = os.path.join(os.path.dirname(__file__), '..', 'data', 'posts.json')

new_posts = [
    {
        "slug": "ahsoka-tano",
        "title_en": "Ahsoka Tano: Walking Between Light and Shadow",
        "title_pl": "Ahsoka Tano: Kroczenie Między Światłem a Cieniem",
        "excerpt_en": "Neither Jedi nor Sith—Ahsoka forged her own path through the Force after surviving Order 66 and the fall of the Republic.",
        "excerpt_pl": "Ani Jedi, ani Sith—Ahsoka wytyczała własną ścieżkę przez Moc po przetrwaniu Rozkazu 66 i upadku Republiki.",
        "content_en": "Ahsoka Tano began as Anakin Skywalker's headstrong Padawan during the Clone Wars and evolved into one of the most compelling figures in Star Wars history. Her journey from eager young Jedi to disillusioned warrior to independent Force-wielder mirrors the galaxy's own turbulent transformation.\n\nDuring the Clone Wars, Ahsoka proved herself an exceptional commander and fighter. She led clone troopers in battle, faced Sith assassins, and earned the respect of seasoned generals. But her defining moment came when the Jedi Council wrongly accused her of terrorism. Though eventually cleared, the experience shattered her faith in the Order.\n\nHer departure from the Jedi—walking down the Temple steps while Anakin watched helplessly—remains one of the most emotionally devastating scenes in Star Wars. She left not because she stopped believing in the Force, but because she stopped believing in the institution.\n\nAfter Order 66, Ahsoka survived by hiding her identity, eventually becoming the covert operative \"Fulcrum\" for the nascent Rebel Alliance. Her white lightsabers, purified from an Inquisitor's red crystals, symbolize her unique position: wielding the Force without allegiance to either Jedi dogma or Sith corruption.\n\nHer confrontation with Darth Vader in the Sith temple on Malachor—facing her former master consumed by the dark side—is heartbreaking. \"I am no Jedi,\" she declares, refusing to abandon him even as she fights for her life.\n\n**Fun Fact:** Ahsoka was originally conceived as a one-off character for the Clone Wars movie but became so popular that Dave Filoni expanded her role across three animated series and a live-action show.",
        "content_pl": "Ahsoka Tano zaczynała jako porywcza Padawan Anakina Skywalkera w czasie Wojen Klonów i wyrosła na jedną z najbardziej fascynujących postaci w historii Star Wars. Jej droga od gorliwej młodej Jedi, przez rozczarowaną wojowniczkę, po niezależną władającą Mocą odzwierciedla burzliwą transformację samej galaktyki.\n\nPodczas Wojen Klonów Ahsoka udowodniła, że jest wyjątkową dowódczynią i wojowniczką. Prowadziła żołnierzy klonów do bitwy, stawiała czoła sithańskim zabójcom i zdobyła szacunek doświadczonych generałów. Ale jej definiujący moment nastąpił, gdy Rada Jedi fałszywie oskarżyła ją o terroryzm. Choć ostatecznie oczyszczona z zarzutów, doświadczenie to roztrzaskało jej wiarę w Zakon.\n\nJej odejście od Jedi—schodzącej po stopniach Świątyni, podczas gdy Anakin patrzył bezradnie—pozostaje jedną z najbardziej emocjonalnie druzgocących scen w Star Wars. Odeszła nie dlatego, że przestała wierzyć w Moc, ale dlatego, że przestała wierzyć w instytucję.\n\nPo Rozkazie 66 Ahsoka przetrwała, ukrywając swoją tożsamość, ostatecznie stając się tajną agentką „Fulcrum" dla rodzącej się Rebelii. Jej białe miecze świetlne, oczyszczone z czerwonych kryształów Inkwizytora, symbolizują jej wyjątkową pozycję: władanie Mocą bez przynależności do dogmatu Jedi czy korupcji Sithów.\n\nJej konfrontacja z Darthem Vaderem w świątyni Sithów na Malachorze—twarzą w twarz z byłym mistrzem pochłoniętym przez ciemną stronę—łamie serce. „Nie jestem Jedi", oświadcza, odmawiając porzucenia go nawet walcząc o własne życie.\n\n**Ciekawostka:** Ahsoka została pierwotnie wymyślona jako jednorazowa postać do filmu Wojny Klonów, ale stała się tak popularna, że Dave Filoni rozszerzył jej rolę na trzy serie animowane i serial aktorski.",
        "category": "character",
        "era": "clone_wars",
        "canon_status": "canon",
        "featured": True,
        "image_prompt": "Togruta warrior woman with white lightsabers in dual stance, orange skin and blue-white montrals, Mandalore siege backdrop, Clone Wars era, epic cinematic lighting"
    },
    {
        "slug": "grand-admiral-thrawn",
        "title_en": "Grand Admiral Thrawn: The Art of War",
        "title_pl": "Wielki Admirał Thrawn: Sztuka Wojny",
        "excerpt_en": "The only alien to reach the Empire's highest military rank—Thrawn studied art to understand his enemies, then destroyed them.",
        "excerpt_pl": "Jedyny obcy, który osiągnął najwyższą rangę wojskową Imperium—Thrawn studiował sztukę, by zrozumieć wrogów, a potem ich niszczyć.",
        "content_en": "Grand Admiral Thrawn, born Mitth'raw'nuruodo of the Chiss Ascendancy, is the Empire's most brilliant military strategist and its most unlikely leader. In an Empire built on human supremacy, a blue-skinned alien with glowing red eyes rose to the highest rank in the Imperial Navy through sheer tactical genius.\n\nThrawn's signature method is cultural analysis through art. He studies the paintings, music, architecture, and crafts of a species to understand their psychology, values, and blind spots. This isn't mere appreciation—it's weaponized anthropology. By understanding how a people express beauty and meaning, Thrawn predicts how they'll fight, flee, and surrender.\n\nHis campaigns against the Rebel Alliance demonstrated this philosophy ruthlessly. Where other Imperial commanders relied on overwhelming firepower, Thrawn used precise, surgical strikes informed by deep understanding of his opponents. He turned Phoenix Squadron's strengths against them, anticipated Hera Syndulla's tactics, and nearly crushed the Rebellion on Lothal.\n\nThrawn's exile to the Unknown Regions with Ezra Bridger didn't end his story. His return, decades later, threatened to reignite Imperial ambitions. His alliance with the Nightsisters and command of a resurgent fleet made him perhaps the most dangerous adversary the New Republic ever faced.\n\nWhat makes Thrawn compelling isn't just his intellect—it's his courtesy. He's polite, appreciative of talent, and genuinely fascinated by other cultures. He's a villain you almost want to succeed.\n\n**Fun Fact:** Thrawn was created by author Timothy Zahn in 1991 for 'Heir to the Empire,' the novel that revived Star Wars fiction and essentially created the Expanded Universe.",
        "content_pl": "Wielki Admirał Thrawn, urodzony jako Mitth'raw'nuruodo z Dominium Chissów, jest najgenialniejszym strategiem wojskowym Imperium i jego najbardziej nieoczekiwanym przywódcą. W Imperium zbudowanym na ludzkiej supremacji, niebieskoskóry obcy z płonącymi czerwonymi oczami wzniósł się na najwyższą rangę w Imperialnej Marynarce dzięki samemu geniuszowi taktycznemu.\n\nMetoda Thrawna to analiza kulturowa przez sztukę. Studiuje malarstwo, muzykę, architekturę i rzemiosło gatunku, by zrozumieć jego psychologię, wartości i słabe punkty. To nie jest zwykłe podziwianie—to uzbrojona antropologia. Rozumiejąc, jak lud wyraża piękno i sens, Thrawn przewiduje, jak będą walczyć, uciekać i kapitulować.\n\nJego kampanie przeciwko Rebelii demonstrowały tę filozofię bezlitośnie. Gdzie inni imperialni dowódcy polegali na przygniatającej sile ognia, Thrawn stosował precyzyjne, chirurgiczne uderzenia oparte na głębokim zrozumieniu przeciwników. Obrócił mocne strony Eskadry Phoenix przeciw nim, przewidywał taktykę Hery Syndulli i niemal zmiażdżył Rebelię na Lothalu.\n\nWygnanie Thrawna do Nieznanych Regionów z Ezrą Bridgerem nie zakończyło jego historii. Jego powrót, dekady później, groził ponownym rozpaleniem imperialnych ambicji. Jego sojusz z Siostrami Nocy i dowodzenie odradzającą się flotą uczyniły go być może najniebezpieczniejszym przeciwnikiem, jakiego kiedykolwiek napotkała Nowa Republika.\n\nTo, co czyni Thrawna fascynującym, to nie tylko jego intelekt—to jego uprzejmość. Jest grzeczny, docenia talent i jest szczerze zafascynowany innymi kulturami. To złoczyńca, któremu prawie chcesz kibicować.\n\n**Ciekawostka:** Thrawn został stworzony przez autora Timothy'ego Zahna w 1991 roku dla powieści 'Heir to the Empire,' która ożywiła fikcję Star Wars i w zasadzie stworzyła Expanded Universe.",
        "category": "character",
        "era": "imperial",
        "canon_status": "canon",
        "featured": True,
        "image_prompt": "Blue-skinned Chiss officer in white Imperial grand admiral uniform, glowing red eyes, studying holographic art display on Star Destroyer bridge, tactical maps in background"
    },
    {
        "slug": "order-66",
        "title_en": "Order 66: The Fall of the Jedi",
        "title_pl": "Rozkaz 66: Upadek Jedi",
        "excerpt_en": "In an instant, the clone soldiers who fought beside the Jedi for years turned their weapons on their generals—and the galaxy changed forever.",
        "excerpt_pl": "W jednej chwili żołnierze klony, którzy walczyli u boku Jedi przez lata, odwrócili broń przeciw swoim generałom—i galaktyka zmieniła się na zawsze.",
        "content_en": "Order 66 was the most devastating betrayal in galactic history. With three words—\"Execute Order 66\"—Chancellor Palpatine activated a contingency protocol hidden in the biochips of every clone trooper, compelling them to kill their Jedi commanders without hesitation or mercy.\n\nThe horror wasn't just in the killing. It was in the intimacy of the betrayal. Jedi and clones had fought side by side for three years of brutal warfare. They had saved each other's lives, shared meals, mourned fallen comrades. Commander Cody, who had served loyally with Obi-Wan Kenobi through countless campaigns, tried to blast him off a cliff without a moment's pause.\n\nAcross the galaxy, the purge unfolded simultaneously. Ki-Adi-Mundi fell on Mygeeto, cut down by the troopers he was leading into battle. Aayla Secura was shot in the back on Felucia. Young Padawans in the Jedi Temple were slaughtered by Darth Vader himself—a man they had known as Anakin Skywalker, hero of the Republic.\n\nThe cruelty of Order 66's design was its perfection. The biochips removed choice from the clones—most of them would have refused the order otherwise. Some, like Captain Rex, resisted long enough for the chip to be removed, but they were the rare exceptions.\n\nIn the aftermath, surviving Jedi were hunted by Inquisitors across the galaxy. The Temple burned. The archives were sealed. A thousand-generation legacy was reduced to scattered survivors hiding in the galaxy's forgotten corners.\n\n**Fun Fact:** The inhibitor chip concept was added by The Clone Wars series. In the original films, the implication was that the clones simply followed orders—the series added moral complexity by showing it wasn't their choice.",
        "content_pl": "Rozkaz 66 był najbardziej druzgocącą zdradą w galaktycznej historii. Trzema słowami—„Wykonać Rozkaz 66"—Kanclerz Palpatine aktywował ukryty w biochipach każdego żołnierza klona protokół, zmuszający ich do zabicia swoich dowódców Jedi bez wahania czy litości.\n\nGroza nie tkwiła tylko w zabijaniu. Tkwiła w intymności zdrady. Jedi i klony walczyli ramię w ramię przez trzy lata brutalnej wojny. Ratowali sobie nawzajem życie, dzielili posiłki, opłakiwali poległych towarzyszy. Dowódca Cody, który służył lojalnie z Obi-Wanem Kenobim przez niezliczone kampanie, próbował zestrzelić go z klifu bez chwili wahania.\n\nW całej galaktyce czystka rozwijała się jednocześnie. Ki-Adi-Mundi padł na Mygeeto, ścięty przez żołnierzy, których prowadził do bitwy. Aayla Secura została zastrzelona w plecy na Felucii. Młodzi Padawani w Świątyni Jedi zostali wymordowani przez samego Dartha Vadera—człowieka, którego znali jako Anakina Skywalkera, bohatera Republiki.\n\nOkrucieństwo konstrukcji Rozkazu 66 tkwiło w jego doskonałości. Biochipy odebrały klonom wybór—większość z nich odmówiłaby rozkazu. Niektórzy, jak Kapitan Rex, oparli się wystarczająco długo, by chip mógł zostać usunięty, ale byli rzadkimi wyjątkami.\n\nW następstwie ocalali Jedi byli ścigani przez Inkwizytorów w całej galaktyce. Świątynia płonęła. Archiwa zostały zapieczętowane. Tysiącpokoleniowe dziedzictwo zostało zredukowane do rozproszonych ocalałych ukrywających się w zapomnianych zakątkach galaktyki.\n\n**Ciekawostka:** Koncepcja chipów hamujących została dodana przez serial Wojny Klonów. W oryginalnych filmach sugerowano, że klony po prostu wykonywały rozkazy—serial dodał moralną złożoność, pokazując, że to nie był ich wybór.",
        "category": "scene",
        "era": "clone_wars",
        "canon_status": "canon",
        "featured": True,
        "image_prompt": "Clone troopers turning weapons on hooded Jedi general in battlefield, emotional betrayal scene, clone helmets expressionless, blue lightsaber ignited in defense, battlefield chaos"
    },
    {
        "slug": "ebon-hawk",
        "title_en": "The Ebon Hawk: Smuggler's Dream from the Old Republic",
        "title_pl": "Ebon Hawk: Marzenie Przemytnika ze Starej Republiki",
        "excerpt_en": "Thousands of years before the Millennium Falcon, another legendary freighter carried heroes across the galaxy's most dangerous regions.",
        "excerpt_pl": "Tysiące lat przed Sokołem Millennium, inny legendarny frachtowiec wiózł bohaterów przez najniebezpieczniejsze regiony galaktyki.",
        "content_en": "The Ebon Hawk is the Millennium Falcon's spiritual ancestor—a nimble, heavily modified freighter that carried some of the Old Republic's most important figures across the galaxy during its darkest hours. Like its successor thousands of years later, the Hawk was fast, tough, and perpetually in need of repair.\n\nOriginally a smuggling vessel, the Ebon Hawk passed through the hands of numerous owners before becoming intertwined with the fate of Revan. During the Jedi Civil War, the ship served as base of operations for Revan's crew as they searched for the Star Maps leading to the Star Forge.\n\nThe Hawk's design reflects an era of rougher, more industrial starship construction. Lacking the Falcon's smooth curves, the Ebon Hawk has an angular, utilitarian appearance—a ship built for function over form. Her cargo holds had been converted into hidden compartments, her engines modified for speed, and her weapons upgraded for combat.\n\nWhat makes the Ebon Hawk special isn't her specifications—it's the conversations that happened aboard her. The ship's main hold became a gathering point for some of the most diverse and conflicted crews in Star Wars history: Jedi, Sith, soldiers, droids, and Mandalorians debating philosophy, purpose, and the nature of the Force.\n\nThe Meetra Surik later used the Hawk during her quest to reunite the Jedi Order, making the ship a witness to two of the Old Republic's most transformative journeys.\n\n**Fun Fact:** The Ebon Hawk was deliberately designed to evoke the Millennium Falcon in Knights of the Old Republic, giving players that same sense of 'home base' that Han Solo's ship provided in the films.",
        "content_pl": "Ebon Hawk to duchowy przodek Sokoła Millennium—zwinny, mocno zmodyfikowany frachtowiec, który wiózł jedne z najważniejszych postaci Starej Republiki przez galaktykę w jej najciemniejszych godzinach. Podobnie jak jego następca tysiące lat później, Hawk był szybki, wytrzymały i nieustannie potrzebujący naprawy.\n\nPoczątkowo statek przemytniczy, Ebon Hawk przeszedł przez ręce licznych właścicieli, zanim jego los splótł się z losem Revana. Podczas Jediańskiej Wojny Domowej, statek służył jako baza operacyjna dla załogi Revana poszukującej Map Gwiezdnych prowadzących do Gwiezdnej Kuźni.\n\nDesign Hawka odzwierciedla erę bardziej surowej, industrialnej konstrukcji statków. Pozbawiony gładkich krzywych Falcona, Ebon Hawk ma kanciasty, utylitarny wygląd—statek zbudowany dla funkcji, nie formy. Jego ładownie zostały przerobione na ukryte schowki, silniki zmodyfikowane pod kątem prędkości, a broń ulepszona do walki.\n\nTo, co czyni Ebon Hawka wyjątkowym, to nie jego specyfikacja—to rozmowy, które odbywały się na jego pokładzie. Główna ładownia statku stała się miejscem spotkań jednych z najbardziej zróżnicowanych i skonfliktowanych załóg w historii Star Wars: Jedi, Sithowie, żołnierze, droidy i Mandalorianie debatujący o filozofii, celu i naturze Mocy.\n\nMeetra Surik później używała Hawka podczas swojej misji zjednoczenia Zakonu Jedi, czyniąc statek świadkiem dwóch najbardziej transformacyjnych podróży Starej Republiki.\n\n**Ciekawostka:** Ebon Hawk został celowo zaprojektowany, by przywoływać Sokoła Millennium w Knights of the Old Republic, dając graczom to samo poczucie „bazy" które statek Hana Solo zapewniał w filmach.",
        "category": "ship",
        "era": "old_republic",
        "canon_status": "legends",
        "featured": False,
        "image_prompt": "Angular Old Republic era freighter ship flying through nebula, rough industrial design, forward mandibles, engines glowing blue, asteroid field in background"
    },
    {
        "slug": "siege-of-mandalore",
        "title_en": "Siege of Mandalore: The Clone Wars' Final Battle",
        "title_pl": "Oblężenie Mandalore: Ostatnia Bitwa Wojen Klonów",
        "excerpt_en": "As the Republic crumbled and Order 66 struck, Ahsoka Tano faced Darth Maul in the battle that bridged the Clone Wars and Revenge of the Sith.",
        "excerpt_pl": "Gdy Republika się rozpadała i uderzył Rozkaz 66, Ahsoka Tano stanęła naprzeciw Dartha Maula w bitwie łączącej Wojny Klonów z Zemstą Sithów.",
        "content_en": "The Siege of Mandalore is the Clone Wars' masterpiece finale—a battle that unfolds simultaneously with the events of Revenge of the Sith, lending devastating context to both stories. While Anakin Skywalker falls to the dark side on Coruscant, Ahsoka Tano fights for survival on Mandalore.\n\nAhsoka, no longer officially a Jedi, leads a division of the 501st Legion—clone troopers who painted their helmets orange in her honor—against Darth Maul's Shadow Collective on Mandalore. The battle begins as a conventional siege but escalates into something far more personal.\n\nAhsoka's duel with Maul in the throne room of Sundari is not just combat—it's a clash of two people who both see the coming catastrophe. Maul knows Sidious's plan and desperately tries to convince Ahsoka to join him in stopping it. When she refuses, their fight becomes a masterwork of choreography and emotion, ending with Ahsoka capturing Maul using the Force to hold him suspended in a collapsing beam structure.\n\nThen Order 66 strikes.\n\nThe final four episodes depict Ahsoka and Captain Rex fighting to survive against their own men—clone troopers they led and loved, now mindlessly trying to kill them. Rex's chip-removal scene, where he resists the programming with tears streaming down his face, gasping \"Find him—find Fives,\" is perhaps the most emotionally raw moment in all of Star Wars animation.\n\nThe series ends with Ahsoka standing alone in the snow, surrounded by clone trooper graves she dug herself. Her lightsaber, abandoned. The Republic, dead.\n\n**Fun Fact:** The final arc was animated in a more cinematic style with a wider aspect ratio, making it visually distinct from the rest of the series—Dave Filoni wanted it to feel like a Star Wars film.",
        "content_pl": "Oblężenie Mandalore to arcydzielne zakończenie Wojen Klonów—bitwa rozgrywająca się jednocześnie z wydarzeniami Zemsty Sithów, nadająca obu historiom druzgocący kontekst. Gdy Anakin Skywalker upada na ciemną stronę na Coruscant, Ahsoka Tano walczy o przetrwanie na Mandalore.\n\nAhsoka, oficjalnie już nie Jedi, prowadzi dywizję 501. Legionu—żołnierzy klonów, którzy pomalowali swoje hełmy na pomarańczowo na jej cześć—przeciwko Zbiorowemu Cieniowi Dartha Maula na Mandalore. Bitwa zaczyna się jako konwencjonalne oblężenie, ale eskaluje w coś znacznie bardziej osobistego.\n\nPojedynek Ahsoki z Maulem w sali tronowej Sundari to nie tylko walka—to starcie dwóch osób, które obie widzą nadchodzącą katastrofę. Maul zna plan Sidiousa i desperacko próbuje przekonać Ahsokę, by dołączyła do niego w powstrzymaniu go. Gdy odmawia, ich walka staje się mistrzowskim dziełem choreografii i emocji, kończąc się schwytaniem Maula przez Ahsokę używającą Mocy, by utrzymać go zawieszonego w rozpadającej się konstrukcji.\n\nWtedy uderza Rozkaz 66.\n\nOstatnie cztery odcinki przedstawiają Ahsokę i Kapitana Rexa walczących o przetrwanie przeciwko własnym ludziom—żołnierzom klonom, którymi dowodzili i których kochali, teraz bezmyślnie próbującym ich zabić. Scena usunięcia chipu Rexa, gdzie opiera się programowaniu ze łzami płynącymi po twarzy, dysząc „Znajdź go—znajdź Fivesa," jest być może najbardziej emocjonalnie surowym momentem w całej animacji Star Wars.\n\nSerial kończy się Ahsoką stojącą samotnie w śniegu, otoczoną grobami żołnierzy klonów, które sama wykopała. Jej miecz świetlny, porzucony. Republika, martwa.\n\n**Ciekawostka:** Ostatni łuk fabularny został animowany w bardziej kinowym stylu z szerszym formatem obrazu, czyniąc go wizualnie odmiennym od reszty serialu—Dave Filoni chciał, by wyglądał jak film Star Wars.",
        "category": "battle",
        "era": "clone_wars",
        "canon_status": "canon",
        "featured": False,
        "image_prompt": "Ahsoka Tano dueling Darth Maul in Mandalorian throne room, orange-painted clone troopers storming the palace, Mandalore burning in background"
    },
    {
        "slug": "darth-nihilus",
        "title_en": "Darth Nihilus: The Lord of Hunger",
        "title_pl": "Darth Nihilus: Pan Głodu",
        "excerpt_en": "A wound in the Force given form—Nihilus consumed entire planets to feed an insatiable hunger that threatened to devour the galaxy itself.",
        "excerpt_pl": "Rana w Mocy, która przybrała formę—Nihilus pochłaniał całe planety, by nakarmić nienasyconą żądzę grożącą pożarciem samej galaktyki.",
        "content_en": "Darth Nihilus is perhaps the most terrifying Sith Lord in Star Wars lore—not because of his power or ambition, but because of what he had become. He was no longer truly a person. He was hunger incarnate, a wound in the Force that consumed all life around him to sustain its own existence.\n\nNihilus was a survivor of the Mandalorian Wars, specifically the activation of the Mass Shadow Generator at Malachor V—a superweapon that killed thousands of Mandalorians and Republic soldiers simultaneously. The trauma of that event, combined with exposure to the resulting wound in the Force, transformed Nihilus into something unprecedented.\n\nHe developed the ability to drain the Force from living beings on a planetary scale. His consumption of Katarr—a Miraluka colony world—killed every living thing on the planet in an instant. Only Visas Marr survived, drawn to him and becoming his apprentice.\n\nWhat makes Nihilus uniquely horrifying is that his power was also his prison. He couldn't stop consuming. His hunger grew with every world he drained, and his physical form deteriorated until he was nothing more than dark side energy held together by his robes and mask. His voice became unintelligible—a distorted, ancient language that only Visas could interpret.\n\nNihilus serves as a cautionary tale about the dark side's ultimate consequence: unchecked power that destroys the wielder. He didn't choose to become a monster—the Force's own wound twisted him into one.\n\n**Fun Fact:** Nihilus's mask became one of the most iconic Sith designs in Star Wars. It appears as a collectible in several games and was the inspiration for various fan interpretations of 'faceless evil' in the franchise.",
        "content_pl": "Darth Nihilus jest być może najbardziej przerażającym Lordem Sithów w historii Star Wars—nie z powodu jego mocy czy ambicji, ale z powodu tego, czym się stał. Nie był już naprawdę osobą. Był głodem wcielonym, raną w Mocy pochłaniającą wszelkie życie wokół siebie, by podtrzymać własną egzystencję.\n\nNihilus był ocalałym z Wojen Mandloriańskich, konkretnie aktywacji Generatora Cienia Masowego na Malachorze V—superbroni, która zabiła jednocześnie tysiące Mandalorian i żołnierzy Republiki. Trauma tego wydarzenia, połączona z ekspozycją na wynikającą ranę w Mocy, przekształciła Nihilusa w coś bezprecedensowego.\n\nRozwinął zdolność wysysania Mocy z żywych istot na planetarną skalę. Jego pochłonięcie Katarr—kolonialnego świata Miraluków—zabiło każdą żywą istotę na planecie w mgnieniu oka. Tylko Visas Marr przeżyła, przyciągnięta do niego i stająca się jego uczennicą.\n\nTo, co czyni Nihilusa wyjątkowo przerażającym, to fakt, że jego moc była też jego więzieniem. Nie mógł przestać pochłaniać. Jego głód rósł z każdym wyssanym światem, a jego fizyczna forma degradowała się, aż został niczym więcej niż energią ciemnej strony utrzymywaną razem przez szaty i maskę. Jego głos stał się niezrozumiały—zniekształcony, starożytny język, który tylko Visas mogła interpretować.\n\nNihilus służy jako przestroga o ostatecznej konsekwencji ciemnej strony: niekontrolowana moc niszcząca jej posiadacza. Nie wybrał bycia potworem—rana w Mocy wykrzywiła go w jedno.\n\n**Ciekawostka:** Maska Nihilusa stała się jednym z najbardziej ikonicznych sithańskich designów w Star Wars. Pojawia się jako kolekcjonerski przedmiot w kilku grach i była inspiracją dla różnych fanowskich interpretacji 'beztwarzowego zła' w franczyzie.",
        "category": "character",
        "era": "old_republic",
        "canon_status": "legends",
        "featured": False,
        "image_prompt": "Spectral Sith Lord in tattered robes and iconic white-red mask, Force drain energy spiraling from dying planet below, ghostly dark side aura, deep space"
    },
    {
        "slug": "world-between-worlds",
        "title_en": "The World Between Worlds: Beyond Time and Space",
        "title_pl": "Świat Między Światami: Poza Czasem i Przestrzenią",
        "excerpt_en": "A mystical plane connecting all moments in time through the Force—where the past, present, and future exist simultaneously.",
        "excerpt_pl": "Mistyczna płaszczyzna łącząca wszystkie momenty w czasie przez Moc—gdzie przeszłość, teraźniejszość i przyszłość istnieją jednocześnie.",
        "content_en": "The World Between Worlds is one of the most profound concepts ever introduced to Star Wars canon. Discovered by Ezra Bridger beneath the Jedi Temple on Lothal, this mystical dimension exists outside normal space-time, connecting moments across history through doorways illuminated by starlight.\n\nThe World manifests as an endless void filled with interconnected pathways and portals. Through these portals, one can observe—and potentially alter—events from any point in time. Voices of Jedi past and future echo through the space: Yoda, Obi-Wan, Qui-Gon, Ahsoka, even Rey and Kylo Ren from decades in the future.\n\nEzra used the World Between Worlds to save Ahsoka Tano from death at the hands of Darth Vader on Malachor. By reaching through a portal into the past, he pulled her out of the collapsing Sith temple moments before Vader's killing blow—proving that the World can indeed change the timeline.\n\nEmperor Palpatine desperately sought access to the World, understanding that control over time itself would make him truly omnipotent. The fact that a Jedi Temple guarded its entrance suggests the Force itself placed safeguards against such abuse.\n\nThe philosophical implications are staggering. If all moments exist simultaneously and are accessible, what does free will mean? The Force appears to use the World as a self-correcting mechanism—allowing intervention only when the cosmic balance requires it.\n\nEzra ultimately sealed the Lothal portal to prevent Palpatine from entering, understanding that some powers must remain beyond anyone's reach.\n\n**Fun Fact:** The World Between Worlds concept was inspired by Dave Filoni's conversations with George Lucas about the nature of the Force, and draws on Joseph Campbell's mythological concept of the 'axis mundi'—the cosmic center connecting heaven and earth.",
        "content_pl": "Świat Między Światami to jedna z najbardziej głębokich koncepcji wprowadzonych do kanonu Star Wars. Odkryty przez Ezrę Bridgera pod Świątynią Jedi na Lothalu, ten mistyczny wymiar istnieje poza normalną czasoprzestrzenią, łącząc momenty w historii przez bramy oświetlone gwiazdami.\n\nŚwiat manifestuje się jako nieskończona pustka wypełniona połączonymi ścieżkami i portalami. Przez te portale można obserwować—i potencjalnie zmieniać—wydarzenia z każdego punktu w czasie. Głosy Jedi z przeszłości i przyszłości odbijają się echem w przestrzeni: Yoda, Obi-Wan, Qui-Gon, Ahsoka, nawet Rey i Kylo Ren z przyszłości oddalonej o dekady.\n\nEzra użył Świata Między Światami, by uratować Ahsokę Tano od śmierci z rąk Dartha Vadera na Malachorze. Sięgając przez portal w przeszłość, wyciągnął ją z rozpadającej się świątyni Sithów na chwilę przed śmiertelnym ciosem Vadera—dowodząc, że Świat rzeczywiście może zmieniać oś czasu.\n\nCesarz Palpatine desperacko szukał dostępu do Świata, rozumiejąc, że kontrola nad samym czasem uczyniłaby go naprawdę wszechmocnym. Fakt, że Świątynia Jedi strzegła jego wejścia, sugeruje, że sama Moc umieściła zabezpieczenia przed takim nadużyciem.\n\nImplikacje filozoficzne są oszałamiające. Jeśli wszystkie momenty istnieją jednocześnie i są dostępne, co oznacza wolna wola? Moc wydaje się używać Świata jako mechanizmu samokorygującego—pozwalając na interwencję tylko gdy kosmiczna równowaga tego wymaga.\n\nEzra ostatecznie zapieczętował portal na Lothalu, by uniemożliwić Palpatine'owi wejście, rozumiejąc, że niektóre moce muszą pozostać poza czyimkolwiek zasięgiem.\n\n**Ciekawostka:** Koncepcja Świata Między Światami była zainspirowana rozmowami Dave'a Filoniego z George'em Lucasem o naturze Mocy i czerpie z mitologicznej koncepcji Josepha Campbella 'axis mundi'—kosmicznego centrum łączącego niebo i ziemię.",
        "category": "lore",
        "era": "rebellion",
        "canon_status": "canon",
        "featured": False,
        "image_prompt": "Mystical void of interconnected glowing pathways and circular portals showing different Star Wars scenes, starlight streaming through, Force energy flowing between doorways, ethereal and cosmic"
    },
    {
        "slug": "korriban-moraband",
        "title_en": "Korriban: Valley of the Dark Lords",
        "title_pl": "Korriban: Dolina Mrocznych Lordów",
        "excerpt_en": "The ancient homeworld of the Sith species and birthplace of the dark side tradition—a desolate world of tombs, temples, and terrible power.",
        "excerpt_pl": "Starożytna ojczyzna gatunku Sithów i kolebka tradycji ciemnej strony—pustynny świat grobowców, świątyń i straszliwej mocy.",
        "content_en": "Korriban—later known as Moraband—is the spiritual heart of the Sith Order. This desolate, red-sanded world in the Outer Rim was the homeworld of the Sith species, and for millennia served as the seat of Sith power, learning, and burial.\n\nThe Valley of the Dark Lords dominates the landscape: a massive canyon lined with enormous stone tombs of ancient Sith Lords. Each tomb is a monument to power and a repository of dark side knowledge, protected by traps, spirits, and dark side energy so concentrated it drives the unprepared insane.\n\nThe Sith Academy on Korriban trained generations of dark side acolytes. Aspiring Sith were sent into the tombs to prove their worth—retrieving artifacts, surviving the dark side spirits within, and demonstrating the ruthlessness required to wield power. Many entered. Few emerged.\n\nThe planet's connection to the dark side is so strong that it warps reality. Visitors experience visions, hear voices of dead Sith, and feel the crushing weight of accumulated centuries of hatred and ambition. Even Yoda, when he visited Moraband during the Clone Wars, faced terrifying illusions conjured by the dark side.\n\nKorriban was abandoned and rediscovered multiple times throughout galactic history, but the dark side never left. The tombs still pulse with power, the spirits still whisper, and the planet still calls to those susceptible to the dark side's seduction.\n\n**Fun Fact:** The planet was called 'Korriban' in Legends material (including KOTOR), but George Lucas renamed it 'Moraband' for The Clone Wars. Both names are now considered canon, with Moraband being the more contemporary name.",
        "content_pl": "Korriban—później znany jako Moraband—to duchowe serce Zakonu Sithów. Ten pustynny, czerwonopiastkowy świat na Zewnętrznym Krawędzi był ojczyzną gatunku Sithów i przez tysiąclecia służył jako siedziba sithańskiej władzy, nauki i pochówku.\n\nDolina Mrocznych Lordów dominuje krajobraz: masywny kanion wyłożony ogromnymi kamiennymi grobowcami starożytnych Lordów Sithów. Każdy grobowiec jest monumentem mocy i repozytorium wiedzy ciemnej strony, chronionym pułapkami, duchami i energią ciemnej strony tak skoncentrowaną, że doprowadza nieprzygotowanych do szaleństwa.\n\nAkademia Sithów na Korribanie szkoliła pokolenia adeptów ciemnej strony. Aspirujący Sithowie byli wysyłani do grobowców, by udowodnić swoją wartość—odzyskując artefakty, przeżywając duchy ciemnej strony w środku i demonstrując bezwzględność wymaganą do władania mocą. Wielu wchodziło. Niewielu wychodziło.\n\nPołączenie planety z ciemną stroną jest tak silne, że zakrzywia rzeczywistość. Odwiedzający doświadczają wizji, słyszą głosy martwych Sithów i czują miażdżący ciężar nagromadzonych wieków nienawiści i ambicji. Nawet Yoda, gdy odwiedził Moraband podczas Wojen Klonów, stanął przed przerażającymi iluzjami wyczarowanymi przez ciemną stronę.\n\nKorriban był porzucany i ponownie odkrywany wielokrotnie w galaktycznej historii, ale ciemna strona nigdy nie odeszła. Grobowce wciąż pulsują mocą, duchy wciąż szepczą, a planeta wciąż woła tych podatnych na uwodzenie ciemnej strony.\n\n**Ciekawostka:** Planeta nazywała się 'Korriban' w materiałach Legends (w tym KOTOR), ale George Lucas przemianował ją na 'Moraband' dla Wojen Klonów. Obie nazwy są teraz uważane za kanon, przy czym Moraband jest bardziej współczesną nazwą.",
        "category": "planet",
        "era": "old_republic",
        "canon_status": "canon",
        "featured": False,
        "image_prompt": "Vast desert canyon lined with enormous ancient stone tombs, red sand and rock under blood-red sky, dark side energy crackling between monuments, Sith statues flanking the valley entrance"
    },
    {
        "slug": "star-forge",
        "title_en": "The Star Forge: Engine of Infinite War",
        "title_pl": "Gwiezdna Kuźnia: Machina Nieskończonej Wojny",
        "excerpt_en": "An ancient Rakatan space station powered by dark side energy and a star's core—capable of producing an endless fleet of warships.",
        "excerpt_pl": "Starożytna stacja kosmiczna Rakatanów zasilana energią ciemnej strony i jądrem gwiazdy—zdolna do produkcji nieskończonej floty okrętów wojennych.",
        "content_en": "The Star Forge was the ultimate weapon of the ancient Rakatan Infinite Empire—a colossal space station that drew power from a nearby star and the dark side of the Force to manufacture an endless supply of warships, battle droids, and war material. It was the pinnacle of dark side technology, and perhaps the most dangerous artifact ever created.\n\nBuilt over 25,000 years before the Battle of Yavin, the Star Forge was the engine behind the Rakatans' galactic conquest. It didn't just build ships—it fed on the dark side energy of its operators, amplifying their aggression and corruption while growing more powerful. The station was essentially alive, a dark side nexus that consumed its users even as it served them.\n\nWhen the Rakatan Infinite Empire collapsed—destroyed by a plague that severed their connection to the Force—the Star Forge was lost. It orbited a forgotten star in an uncharted system, protected by a disruptor field that scrambled navigation computers, waiting to be found again.\n\nRevan rediscovered the Star Forge after following a trail of Star Maps scattered across the galaxy. As a Sith Lord, he used it to build a massive fleet that nearly conquered the Republic. Later, redeemed and memory-wiped, Revan returned to destroy the station he had once used, understanding that the Star Forge would corrupt anyone who wielded it.\n\nThe station's destruction in the Battle of the Star Forge was one of the pivotal moments of the Old Republic era, ending the Jedi Civil War and demonstrating that some sources of power are too dangerous to exist.\n\n**Fun Fact:** The Star Forge's design in KOTOR was partially inspired by a Dyson sphere concept—a megastructure that completely encompasses a star to harvest its energy output.",
        "content_pl": "Gwiezdna Kuźnia była ostateczną bronią starożytnego Nieskończonego Imperium Rakatanów—kolosalną stacją kosmiczną czerpiącą moc z pobliskiej gwiazdy i ciemnej strony Mocy do wytwarzania nieskończonych zapasów okrętów wojennych, droidów bojowych i materiałów wojennych. Była szczytem technologii ciemnej strony i być może najniebezpieczniejszym artefaktem, jaki kiedykolwiek stworzono.\n\nZbudowana ponad 25 000 lat przed Bitwą o Yavin, Gwiezdna Kuźnia była silnikiem rakatańskiego galaktycznego podboju. Nie tylko budowała statki—karmiła się energią ciemnej strony swoich operatorów, wzmacniając ich agresję i korupcję, jednocześnie stając się potężniejsza. Stacja była w zasadzie żywa, nexusem ciemnej strony pochłaniającym swoich użytkowników nawet gdy im służyła.\n\nGdy Nieskończone Imperium Rakatanów upadło—zniszczone przez plagę, która odcięła ich połączenie z Mocą—Gwiezdna Kuźnia została utracona. Orbitowała wokół zapomnianej gwiazdy w niezmapowanym systemie, chroniona polem zakłócającym komputery nawigacyjne, czekając na ponowne odkrycie.\n\nRevan ponownie odkrył Gwiezdną Kuźnię po prześledzeniu szlaku Map Gwiezdnych rozsianych po galaktyce. Jako Lord Sithów użył jej do zbudowania masowej floty, która niemal podbiła Republikę. Później, odkupiony i z wymazaną pamięcią, Revan wrócił, by zniszczyć stację, którą niegdyś używał, rozumiejąc, że Gwiezdna Kuźnia skorumpuje każdego, kto nią władał.\n\nZniszczenie stacji w Bitwie o Gwiezdną Kuźnię było jednym z przełomowych momentów ery Starej Republiki, kończąc Jediańską Wojnę Domową i demonstrując, że niektóre źródła mocy są zbyt niebezpieczne, by istnieć.\n\n**Ciekawostka:** Design Gwiezdnej Kuźni w KOTOR był częściowo zainspirowany koncepcją sfery Dysona—megastruktury całkowicie otaczającej gwiazdę w celu pozyskania jej energii.",
        "category": "timeline",
        "era": "old_republic",
        "canon_status": "legends",
        "featured": False,
        "image_prompt": "Massive ancient space station orbiting close to a star, energy beams drawn from the star into the station, fleet of warships emerging from construction bays, dark metallic alien architecture"
    },
    {
        "slug": "battle-of-malachor",
        "title_en": "Battle of Malachor: The Ancient Cataclysm",
        "title_pl": "Bitwa o Malachor: Starożytny Kataklizm",
        "excerpt_en": "A devastating clash between Jedi and Sith that turned an entire world into a petrified graveyard—and created one of the deadliest wounds in the Force.",
        "excerpt_pl": "Druzgocące starcie między Jedi a Sithami, które zamieniło cały świat w skamieniony cmentarz—i stworzyło jedną z najgroźniejszych ran w Mocy.",
        "content_en": "The Battle of Malachor is one of the most catastrophic events in galactic history—a conflict so devastating that it scarred both the planet and the Force itself. Two versions of this battle exist in Star Wars lore, both carrying immense weight.\n\nIn the ancient past, a massive battle between the Jedi and the Sith took place on Malachor. A superweapon within the Sith temple was activated during the fighting, instantly petrifying every combatant on the battlefield. Thousands of years later, when Ahsoka Tano, Kanan Jarrus, and Ezra Bridger explored the planet, they found the battlefield exactly as it was frozen—Jedi and Sith locked in combat for eternity, lightsabers still clutched in stone hands.\n\nDuring the Mandalorian Wars, Malachor V became the site of another apocalyptic battle. The Jedi General known as the Exile activated the Mass Shadow Generator, a gravity-based superweapon that crushed both the Mandalorian fleet and a significant portion of the Republic's own forces. The screams of thousands dying simultaneously through the Force created a wound so deep that it would produce Darth Nihilus.\n\nMalachor represents the ultimate consequence of unchecked warfare. Both battles demonstrate that pursuing victory at any cost—whether through Sith superweapons or Republic desperation—leads to devastation that echoes through millennia.\n\nThe Sith temple on Malachor later became the site of Ahsoka's confrontation with Darth Vader, adding yet another layer of tragedy to a world defined by it.\n\n**Fun Fact:** The petrified battlefield scene in Star Wars Rebels was inspired by the ruins of Pompeii, where volcanic ash preserved the final moments of an ancient civilization.",
        "content_pl": "Bitwa o Malachor to jedno z najbardziej katastroficznych wydarzeń w galaktycznej historii—konflikt tak druzgocący, że zostawił bliznę zarówno na planecie, jak i na samej Mocy. Dwie wersje tej bitwy istnieją w Star Wars, obie niosąc ogromny ciężar.\n\nW starożytnej przeszłości masowa bitwa między Jedi a Sithami miała miejsce na Malachorze. Superbroń wewnątrz świątyni Sithów została aktywowana podczas walki, natychmiast petryfikując każdego kombatanta na polu bitwy. Tysiące lat później, gdy Ahsoka Tano, Kanan Jarrus i Ezra Bridger eksplorowali planetę, znaleźli pole bitwy dokładnie takie, jakim zostało zamrożone—Jedi i Sithowie zamknięci w walce na wieczność, miecze świetlne wciąż zaciśnięte w kamiennych dłoniach.\n\nPodczas Wojen Mandloriańskich, Malachor V stał się miejscem kolejnej apokaliptycznej bitwy. Generał Jedi znany jako Wygnaniec aktywował Generator Cienia Masowego, superbroń opartą na grawitacji, która zmiażdżyła zarówno flotę Mandalorian, jak i znaczną część własnych sił Republiki. Krzyki tysięcy umierających jednocześnie przez Moc stworzyły ranę tak głęboką, że zrodziła Dartha Nihilusa.\n\nMalachor reprezentuje ostateczną konsekwencję niekontrolowanej wojny. Obie bitwy demonstrują, że dążenie do zwycięstwa za wszelką cenę—czy przez superbronie Sithów, czy desperację Republiki—prowadzi do dewastacji odbijającej się echem przez tysiąclecia.\n\nŚwiatynia Sithów na Malachorze później stała się miejscem konfrontacji Ahsoki z Darthem Vaderem, dodając kolejną warstwę tragedii do świata definiowanego przez nią.\n\n**Ciekawostka:** Scena skamienionego pola bitwy w Star Wars Rebels była zainspirowana ruinami Pompejów, gdzie popiół wulkaniczny utrwalił ostatnie chwile starożytnej cywilizacji.",
        "category": "timeline",
        "era": "old_republic",
        "canon_status": "canon",
        "featured": False,
        "image_prompt": "Vast petrified battlefield with stone-frozen Jedi and Sith warriors mid-combat, lightsabers crystallized in their hands, cracked red earth, Sith temple pyramid in background, eerie twilight atmosphere"
    }
]

with open(POSTS_FILE) as f:
    posts = json.load(f)

existing_slugs = {p['slug'] for p in posts}
added = 0
for p in new_posts:
    if p['slug'] not in existing_slugs:
        # Set image_url
        p['image_url'] = f"/images/posts/{p['slug']}.webp"
        posts.append(p)
        added += 1
        print(f"+ {p['slug']} ({p['category']}/{p['era']})")
    else:
        # Update image_url for existing
        for ep in posts:
            if ep['slug'] == p['slug'] and not ep.get('image_url'):
                ep['image_url'] = f"/images/posts/{p['slug']}.webp"
                print(f"~ {p['slug']} (updated image_url)")

with open(POSTS_FILE, 'w') as f:
    json.dump(posts, f, indent=2, ensure_ascii=False)

print(f"\nAdded {added} posts. Total: {len(posts)}")
